server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/realworld
    username: postgres
    password: postgres

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

realworld:
  jwt.key: some-key

logging.level:
  web: debug
  sql: debug
  cn.sabercon.realworld: debug
