CREATE TABLE "user"
(
    "id"         VARCHAR PRIMARY KEY,
    "email"      VARCHAR     NOT NULL UNIQUE,
    "username"   VARCHAR     NOT NULL UNIQUE,
    "password"   VARCHAR     NOT NULL,
    "bio"        VARCHAR,
    "image"      VARCHAR,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "user_follow"
(
    "follower_id" VARCHAR     NOT NULL,
    "followee_id" VARCHAR     NOT NULL,
    "created_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at"  TIMESTAMPTZ,
    PRIMARY KEY ("follower_id", "followee_id")
);

CREATE TABLE "article"
(
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "author_id"   VARCHAR     NOT NULL,
    "slug"        VARCHAR     NOT NULL UNIQUE,
    "title"       VARCHAR     NOT NULL,
    "description" VARCHAR     NOT NULL,
    "body"        VARCHAR     NOT NULL,
    "created_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at"  TIMESTAMPTZ
);

CREATE TABLE "user_article_favorite"
(
    "user_id"    VARCHAR     NOT NULL,
    "article_id" BIGINT      NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ,
    PRIMARY KEY ("user_id", "article_id")
);

CREATE TABLE "tag"
(
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       VARCHAR     NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "article_tag"
(
    "article_id" BIGINT      NOT NULL,
    "tag_id"     BIGINT      NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ,
    PRIMARY KEY ("article_id", "tag_id")
);

CREATE TABLE "comment"
(
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "author_id"  VARCHAR     NOT NULL,
    "article_id" BIGINT      NOT NULL,
    "body"       VARCHAR     NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);
