name: Kover

on: pull_request

jobs:
  kover:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - name: Generate Kover coverage report
        run: ./gradlew koverXmlReport

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/build/reports/kover/xml/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Test Coverage
          update-comment: true
          min-coverage-overall: 50
          min-coverage-changed-files: 50
